"""add user config fields

Revision ID: a3efc4a4fe37
Revises: 31bd7c4e5dfb
Create Date: 2026-02-15 23:28:08.469941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3efc4a4fe37'
down_revision: Union[str, Sequence[str], None] = '31bd7c4e5dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('job_titles', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('work_models', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('employment_types', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('company_styles', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('industries', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_server', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('reason_for_search', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('open_to_relocation', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('availability', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_preferences_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_preferences_complete')
    op.drop_column('users', 'availability')
    op.drop_column('users', 'open_to_relocation')
    op.drop_column('users', 'reason_for_search')
    op.drop_column('users', 'current_status')
    op.drop_column('users', 'smtp_port')
    op.drop_column('users', 'smtp_server')
    op.drop_column('users', 'smtp_password')
    op.drop_column('users', 'smtp_email')
    op.drop_column('users', 'openai_api_key')
    op.drop_column('users', 'gemini_api_key')
    op.drop_column('users', 'industries')
    op.drop_column('users', 'benefits')
    op.drop_column('users', 'company_styles')
    op.drop_column('users', 'employment_types')
    op.drop_column('users', 'work_models')
    op.drop_column('users', 'job_titles')
    op.drop_column('resumes', 'description')
    # ### end Alembic commands ###
