"""Add whatsapp azure to users

Revision ID: d6e3a935734e
Revises: f21520c5f902
Create Date: 2026-02-16 11:34:54.555237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e3a935734e'
down_revision: Union[str, Sequence[str], None] = 'f21520c5f902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_api_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('whatsapp_phone_number_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('whatsapp_business_account_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('azure_document_endpoint', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('azure_document_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'azure_document_key')
    op.drop_column('users', 'azure_document_endpoint')
    op.drop_column('users', 'whatsapp_business_account_id')
    op.drop_column('users', 'whatsapp_phone_number_id')
    op.drop_column('users', 'whatsapp_api_token')
    # ### end Alembic commands ###
