"""Add pros cons to jobs

Revision ID: f21520c5f902
Revises: a3efc4a4fe37
Create Date: 2026-02-16 11:12:53.706235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21520c5f902'
down_revision: Union[str, Sequence[str], None] = 'a3efc4a4fe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('pros', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('cons', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cons')
    op.drop_column('jobs', 'pros')
    # ### end Alembic commands ###
