@echo off
echo Parando servidor antigo...
taskkill /F /IM python.exe > NUL 2>&1

echo Iniciando servidor Uvicorn...
start /B venv\Scripts\python -m uvicorn app.main:app --port 8001 > uvicorn_output.log 2>&1

echo Aguardando inicializacao...
timeout /t 5 /nobreak > NUL

echo Rodando Teste WhatsApp...
venv\Scripts\python test_whatsapp_local.py
